# version: '3'

# services:
#   web:
#     build: .
#     ports:
#       - "5173:5173"
#     # networks:
#     #   - imanzi
#     # command: ["npm", "run", "start"]

# # networks:
# #   imanzi:
# #     driver: bridge

version: "3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code/src
      - /code/node_modules
    environment:
      - NODE_ENV=development
